### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by FiloSottile** [richfelker/musl-cross-make#10]
If you tag a release of this toolkit, I can make a Homebrew formula for it, and make one-click pre-built cross-compilers available for OS X :)

Literally just add a git version tag, I'll take care of the rest.

**Comment by FiloSottile** [comment]
Here's the Formula draft

https://gist.github.com/FiloSottile/01d2bbfaf63ae1b6e373e6bc874fefc6

**Comment by richfelker** [comment]
Pushed tag v0.9.0.
