### ISSUE TITLE
Why isn't the dynamic linker (loader) a symlink to libc.so?

### ISSUE THREAD

**Issue by firasuke** [richfelker/musl-cross-make#101]
A quick `ls -l` on the `output` directory shows:

```Ls
...
lrwxrwxrwx. 1 firasuke firasuke       12 May 15 14:27 ld-musl-x86_64.so.1 -> /lib/libc.so
...
```

that `ld-musl-x86_64.so.1` is a symlink to `/lib/libc.so` which happens to be where the host's C library is located in most distributions (except on Fedora where it's in `lib64`).

Shouldn't the dynamic linker `ld-musl-x86_64.so.1` be a symlink to the `libc.so` (in the same directory) provided by musl itself (`ld-musl-x86_64.so.1 -> libc.so`)?

**Comment by richfelker** [comment]
Don't think of it as a symlink to the host libc. It's a symlink in the namespace of the target system that's not meaningful on the host system if host!=target, and this isn't a problem because it's not used on the host system.

However, others have pointed out that it's annoying when you want to use qemu-user or such on the host system to test target binaries. So I think it should be made into a relative symlink, but the layer this needs to happen at is musl not mcm, and what's blocking it is a clean makefile expression for generating the right number of `../` instances to match the number of components in `$(libdir)`.

**Comment by firasuke** [comment]
I see.

I'm actually using a patch of mine to change it into a relative symlink:

<https://github.com/glaucuslinux/glaucus/blob/master/cerata/musl/patches/glaucus/0001-remove-libdir.patch>

Correct flags have to be specified though in the recipe file (like `prefix` and `syslibdir` with no `DESTDIR` to prevent problems):

<https://github.com/glaucuslinux/glaucus/blob/master/cerata/musl/native.ceras>

<https://github.com/glaucuslinux/glaucus/blob/master/cerata/musl/system.ceras>

**Comment by richfelker** [comment]
Your patch supposed `$(syslibdir) == $(libdir)` which is never the case in normal usage (`/lib` vs `/usr/lib`).

`--syslibdir=$TOOL/lib` is wrong stuff you copied from LFS. It's a breaking change and absolutely not necessary.

**Comment by firasuke** [comment]
Yes, I understand that it isn't normal behaviour as I don't plan on having `/lib` at all in the root filesystem (only `/usr/lib).

LFS doesn't actually use `musl`, and I tried to recreate what LFS does with Glibc (and the entire toolchain in general) to get something working with musl with two builds only since most implementations of LFS with musl use at least 3 builds to get correct binutils and GCC working and linking to the correct stuff.

**Comment by richfelker** [comment]
Having `/lib` in the target root is perfectly correct; that's the only correct place for ldso to go. However normally `libc.so` and other libs, and includes, go under `/usr/lib` and `/usr/include`. You're not obligated to use that structure, and some people doing LFS-type stuff prefer not to have a `/usr`, but mcm is not going to impose that on your target. The only ABI requirement is that ldso be in `/lib` with the right name.

As I mentioned on the other issue, there's a lot of great stuff about LFS, but its procedure for bootstrapping the compiler toolchain and libc is really really bad. You don't need more than one initial cross compiler (to cross from your potentially-non-musl original host to musl target) and one native compiler (which you cross-compile using the first one). Part of how LFS makes such a mess of it is by not having a good cross-compiling division, but muddling the stages before and after chroot. The right way to do this is just cross-compiling enough stuff, including the native toolchain, to be able to chroot in and do everything else from there, with no `/tools` mess.

**Comment by firasuke** [comment]
Ok closing this issue, thanks for your time!
