### ISSUE TITLE
Select GCC_VER doesn't work.

### ISSUE THREAD

**Issue by huguesBouvier** [richfelker/musl-cross-make#110]
If that option is activated we get: make: *** No rule to make target 'gcc-7.2.0', needed by 'install'.  Stop.
See: https://travis-ci.org/github/messense/rust-musl-cross/jobs/638295318

I have tried GCC_VER = 7.2.0 and more.
https://github.com/messense/rust-musl-cross/issues/27

**Comment by ryanwoodsmall** [comment]
GCC 7.2.0 support was removed in January:

- https://github.com/richfelker/musl-cross-make/commit/49f489e5c6ece5ebaf6b01542f9672dcea99495b

If you're using master, you can glean what's supported from the patches and hashes directories:

- https://github.com/richfelker/musl-cross-make/tree/master/patches
- https://github.com/richfelker/musl-cross-make/tree/master/hashes

**Comment by huguesBouvier** [comment]
Thank you for the answer!
