### ISSUE TITLE
ftp.barfooze.de is down

### ISSUE THREAD

**Issue by schell** [richfelker/musl-cross-make#122]
`make` loops forever on a timeout from http://ftp.barfooze.de. Related ticket here https://github.com/sabotage-linux/kernel-headers/issues/21. Maybe we should add a blurb about how to configure a different LINUX_HEADERS_SITE and payload?

Thanks for all your work on this project, BTW, it looks very promising.

**Comment by rofl0r** [comment]
works for me.

**Comment by schell** [comment]
I'm trying it again...

**Comment by schell** [comment]
Got past the loop, thanks.
