### ISSUE TITLE
how long does it usually take ;-;?

### ISSUE THREAD

**Issue by NTT1906** [richfelker/musl-cross-make#136]
i've been running this for over 2 hours and get a error at the final ;-;
i can't copy the error but i'm trying to do this in termux android 

sorry for bad English and poorly information about the problem

**Comment by richfelker** [comment]
Depending on the speed of your Android device, that might be within the realm of normal. Can you post a screenshot of the error? I'm guessing your termux environment is missing some software needed.

**Comment by NTT1906** [comment]
> Depending on the speed of your Android device, that might be within the realm of normal. Can you post a screenshot of the error? I'm guessing your termux environment is missing some software needed.

i'm running from the start again because i forgot to screenshot it :'<
btw, thanks for fast replying ^^
my first warning is something like `warning: unknown warning option '-Wshadow=local' [-Wunknown-warning-option]` 
my config.mak only has `TARGET = aarch64-linux-musl`
my android version is 11
my termux information is
```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
curl/stable 7.79.0 aarch64 [upgradable from: 7.78.0]
libcurl/stable 7.79.0 aarch64 [upgradable from: 7.78.0]
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Wed Aug 25 16:29:10 CST 2021 aarch64 Android
Device manufacturer:
vivo
```

**Comment by NTT1906** [comment]
![Screenshot_20210917_000137](https://user-images.githubusercontent.com/54394881/133654575-f979c705-1a50-45cc-9efd-26f7c124afad.jpg)
also is this normal?

**Comment by NTT1906** [comment]
![Screenshot_20210917_002835](https://user-images.githubusercontent.com/54394881/133657937-4e78edba-e1e2-4bd0-86d6-1e1d77644759.jpg)
it ended like this...

**Comment by richfelker** [comment]
I'm not familiar with termux so I asked around a little, and as I understand it, by default it does not provide a standards-honoring environment but one using the host Android Bionic as its libc, which has lots of bugs and is likely not capable of hosting gcc. Apparently they have a feature called a "proot" you can install a real distro inside, which should suffice to build mcm.

**Comment by NTT1906** [comment]
> I'm not familiar with termux so I asked around a little, and as I understand it, by default it does not provide a standards-honoring environment but one using the host Android Bionic as its libc, which has lots of bugs and is likely not capable of hosting gcc. Apparently they have a feature called a "proot" you can install a real distro inside, which should suffice to build mcm.

but proot is so slow :<, it will take me a day

**Comment by NTT1906** [comment]
![Screenshot_20210917_084212](https://user-images.githubusercontent.com/54394881/133727202-fabaa98d-d98a-4638-aa99-7762343d31c3.jpg)
same issues :<

**Comment by richfelker** [comment]
I'm not sure what to tell you without knowing termux better. Can you cross-compile your toolchain from a more capable system where it doesn't take so long, and move the result to your Android device?

**Comment by NTT1906** [comment]
> I'm not sure what to tell you without knowing termux better. Can you cross-compile your toolchain from a more capable system where it doesn't take so long, and move the result to your Android device?

okay, sound good ^^
