### ISSUE TITLE
How to change musl version?

### ISSUE THREAD

**Issue by Dennis-Bbg** [richfelker/musl-cross-make#139]
Does musl-cross-make support specifying a musl-version to be used?
I need to use musl-1.1.20 instead of musl 1.2.x, but musl-cross-make automatically downloads the newer version.
How to build the cross compiler with musl-1.1.20?

Within the makefile, the version to be used can be specified. If it is intended to use this, please give a short comment about this in the readme. Thanks :)

**Comment by ryanwoodsmall** [comment]
The default is set in the top-level Makefile: https://github.com/richfelker/musl-cross-make/blob/master/Makefile#L7

To override, add `MUSL_VER = 1.1.20` to your config.mak file.

The pattern is commented in the example config.mak.dist with an example of pulling from Git's master branch: https://github.com/richfelker/musl-cross-make/blob/master/config.mak.dist#L37

**Comment by Dennis-Bbg** [comment]
Thanks! :)
