### ISSUE TITLE
Native build requires backported gcc patch

### ISSUE THREAD

**Issue by michaelforney** [richfelker/musl-cross-make#15]
I ran into https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66259 when trying to build a native toolchain using musl-cross-make. It looks like a fix went into gcc 6.1, but not 5.3.

The patch seemed to apply fine to the gcc_5_3_0_release tag apart from the ChangeLog files. Using `git cherry-pick -X ours e757a6a8` did the trick.

**Comment by MattZhao** [comment]
Hi, I am trying to add gcc5.3 to alpine3.8. The machine is x86_64 and the following is a list of packages I have installed:

bash-4.4# apk list
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No such file or directory
wget-1.19.5-r0 x86_64 {wget} (GPL-3.0-or-later) [installed]
nghttp2-libs-1.32.0-r0 x86_64 {nghttp2} (MIT) [installed]
musl-1.1.19-r10 x86_64 {musl} (MIT) [installed]
bash-4.4.19-r1 x86_64 {bash} (GPL-3.0-or-later) [installed]
libcurl-7.61.1-r0 x86_64 {curl} (MIT) [installed]
git-2.18.1-r0 x86_64 {git} (GPL-2.0-or-later) [installed]
ncurses-libs-6.1_p20180818-r1 x86_64 {ncurses} (MIT) [installed]
zlib-1.2.11-r1 x86_64 {zlib} (zlib) [installed]
apk-tools-2.10.1-r0 x86_64 {apk-tools} (GPL2) [installed]
libssh2-1.8.0-r3 x86_64 {libssh2} (BSD) [installed]
readline-7.0.003-r0 x86_64 {readline} (GPL) [installed]
make-4.2.1-r2 x86_64 {make} (GPL-3.0-or-later) [installed]
musl-utils-1.1.19-r10 x86_64 {musl} (MIT BSD GPL2+) [installed]
ncurses-terminfo-base-6.1_p20180818-r1 x86_64 {ncurses} (MIT) [installed]
alpine-baselayout-3.1.0-r0 x86_64 {alpine-baselayout} (GPL-2.0) [installed]
ca-certificates-20171114-r3 x86_64 {ca-certificates} (MPL-2.0 GPL-2.0-or-later) [installed]
alpine-keys-2.1-r1 x86_64 {alpine-keys} (MIT) [installed]
busybox-1.28.4-r1 x86_64 {busybox} (GPL-2.0) [installed]
libressl2.7-libcrypto-2.7.4-r0 x86_64 {libressl} (custom) [installed]
scanelf-1.2.3-r0 x86_64 {pax-utils} (GPL-2.0) [installed]
libressl2.7-libtls-2.7.4-r0 x86_64 {libressl} (custom) [installed]
libc-utils-0.7.1-r0 x86_64 {libc-dev} (BSD) [installed]
ssl_client-1.28.4-r1 x86_64 {busybox} (GPL-2.0) [installed]
ncurses-terminfo-6.1_p20180818-r1 x86_64 {ncurses} (MIT) [installed]
expat-2.2.5-r0 x86_64 {expat} (MIT) [installed]
pcre2-10.31-r0 x86_64 {pcre2} (BSD-3-Clause) [installed]
libressl2.7-libssl-2.7.4-r0 x86_64 {libressl} (custom) [installed]

I set output to /usr/local and when I call make, I get the following error:

 all_defaults="abi cpu arch tune schedule float mode fpu divide"
 for option in $all_defaults
patching file gcc/gcc.c
patching file gcc/config.gcc
patching file gcc/config/sh/constraints.md
patching file gcc/config/sh/linux.h
patching file gcc/config/sh/sh-c.c
patching file gcc/config/sh/sh-mem.cc
patching file gcc/config/sh/sh-protos.h
patching file gcc/config/sh/sh.c
patching file gcc/config/sh/sh.h
patching file gcc/config/sh/sh.md
patching file gcc/config/sh/sh.opt
patching file gcc/doc/install.texi
patching file gcc/doc/invoke.texi
patching file include/longlong.h
patching file libitm/config/sh/sjlj.S
patching file gcc/config/sh/sh.md (working copy)
patch: can't open 'gcc/config/sh/sh.md (working copy)': No such file or directory
make: *** [Makefile:113: gcc-5.3.0] Error 1

Do you think my error is related to what you have encountered?

**Comment by rofl0r** [comment]
```
./patches/gcc-5.3.0/0008-shsibcall.diff:+++ b/gcc/config/sh/sh.md (working copy)
./patches/gcc-5.2.0/0008-shsibcall.diff:+++ b/gcc/config/sh/sh.md (working copy)
```
seems your patch program doesn't like that string in that patch. removing the " (working copy)" part should fix it

**Comment by MattZhao** [comment]
Thank you! Will try that tomorrow!

**Comment by michaelforney** [comment]
This original issue is now obsolete since musl-cross-make now builds gcc and binutils in separate trees (since defdbb4505).
