### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by nerfpops** [richfelker/musl-cross-make#150]
May I ask for release packages of this project? I'm writing a tutorial that uses this, and pointing to a specific release would make for less potential errors + this is the only thing requiring git in my tutorial, and would love to remove that dependency.

**Comment by rofl0r** [comment]
https://github.com/richfelker/musl-cross-make/archive/fe915821b652a7fa37b34a596f47d8e20bc72338.tar.gz

**Comment by nerfpops** [comment]
Thanks!
