### ISSUE TITLE
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.

### ISSUE THREAD

**Issue by skychengzhixing** [richfelker/musl-cross-make#151]
hi，I run the following command：make TARGET=x86_64-linux-musl install ，but I encountered the following problems：

--2022-05-25 11:15:30--  (try:20)  http://ftp.barfooze.de/pub/sabotage/tarballs/
Found ftp.barfooze.de in host_name_addresses_map (0x555d60601a40)
Connecting to ftp.barfooze.de (ftp.barfooze.de)|5.9.157.210|:80... connected.
Created socket 3.
Releasing 0x0000555d60601a40 (new refcount 1).

HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Closed fd 3

How can I solve this problem

**Comment by rofl0r** [comment]
see solutions mentioned here https://github.com/richfelker/musl-cross-make/issues/128

or just try again, the server is online now.

**Comment by skychengzhixing** [comment]
> see solutions mentioned here #128
> 
> or just try again, the server is online now.

1. Thank you very much for your reply.  I solved the problem I encountered, according to your method!
I made the following changes:
In makeflie at the top, I modified the site to get Linux headers：
+LINUX_HEADERS_SITE = http://mirrors.2f30.org/sabotage/tarballs/
+#LINUX_HEADERS_SITE = http://ftp.barfooze.de/pub/sabotage/tarballs/
Then it can run normally！

2. I have another question for you to answer:
    I want to compile a cross tool chain. The requirements are as follows:
   （1）gcc version：10.3.1
   （2）musl version：1.2.0
   （3）Architecture： aarch64
    Then I just need to make the following modifications:
     1.  In makeflie at the top，modify GCC_VER = 10.3.1 MUSL_VER = 1.2.0；
     2. then run make TARGET=aarch64-linux-musl install 
     So I can output the tool chain I want？

We look forward to your reply！

**Comment by rofl0r** [comment]
> modify GCC_VER = 10.3.1

from what i can tell there's no gcc version 10.3.1, only 10.3.0. in any case, only gcc versions listed in patches/ directory are supported. but with that changed, what you wrote above should work.

**Comment by skychengzhixing** [comment]
Thank you for your answer. Your answer is very helpful to me.

Good wishes to you！

**Comment by skychengzhixing** [comment]
This problem has been solved perfectly, so close it now！
