### ISSUE TITLE
How to change dynamic links into static links?

### ISSUE THREAD

**Issue by skychengzhixing** [richfelker/musl-cross-make#153]
hi，friend：
I compile the tool chain with the following command:
make TARGET=aarch64-linux-musl install
but，I have a question to ask: in the output directory, the generated strip and ranlib are all dynamically linked. How can these be changed into static links?
For example:
command：file ranlib
result：ranlib: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=bfcf15402fed49bc4da99d35e2c809c5285b7ae8, for GNU/Linux 3.2.0, with debug_info, not stripped

**Comment by richfelker** [comment]
`config.mak.dist` has examples for how to do this. You have to setup `COMMON_CONFIG` (passed to binutils and gcc configure) to set `CC` and `CXX` to a static-linking compiler command that works even when libtool hijacks `-static`. That's what the additional `--static` in the example does.

**Comment by skychengzhixing** [comment]
hi，friend：
I added this attribute in the directory litecross/makefile:
COMMON_CONFIG = CC="aarch64-linux-musl-gcc -static --static" CXX="aarch64-linux-musl-g++ -static --static"
But nothing has taken effect. Can you help me see if there is any problem with my operation?

**Comment by skychengzhixing** [comment]
in /build/local/aarch64-linux-musl/config.mak ，I added :
COMMON_CONFIG += CC="aarch64-linux-musl-gcc -static --static" CXX="aarch64-linux-musl-g++ -static --static"
But nothing has taken effect.

**Comment by skychengzhixing** [comment]
hi ,friend:
I made the following changes. I wrote a config.mak. The following contents are added to it:
**
TARGET=aarch64-linux-musl
OUTPUT = /home/zhixing/cheng/11/output
COMMON_CONFIG += CC="aarch64-linux-musl-gcc -static --static" CXX="aarch64-linux-musl-g++ -static --static"
**
Then I execute the following command to compile:
**
make install
**
Operation result feedback:：
The output result path has changed, but this setting as a static link has no effect. Use the following command to view:
1.cd aarch64-linux-musl/bin/
2. file strip 
result：
strip: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9149af731c6dd27089078f75bc44eed5a3e14369, for GNU/Linux 3.2.0, with debug_info, not stripped

This is still a dynamic link！

**Comment by rofl0r** [comment]
did you `make clean` before that ?

**Comment by skychengzhixing** [comment]
hi，friend：
Thank you for your reply，after I make clean, I compile x86_ 64 statically linked tool chain. Results are output；
but，When I want to compile the static tool chain related to aarch64, an error is reported:
**
../../../src_gcc/libgcc/unwind-dw2.c:41:10: fatal error: sys/sdt.h: No such file or directory
   41 | #include <sys/sdt.h>
**
Compilation commands I use:
**
 make HOST=aarch64-linux-musl install
**
Is this command correct?
Can you help me see what caused this?

**Comment by ryanwoodsmall** [comment]
What exactly is your end goal here? Compiling aarch64 code on x86_64? If that's the case, something like this should work:

```
# "native" x86_64
# probably/actually a cross compiler if using distro-provided gcc/glibc on debian/ubuntu/rhel/fedora/etc.
if [ ! -e /tmp/x86_64-linux-musl ] ; then
  cat>config.mak<<EOF
TARGET = x86_64-linux-musl
OUTPUT = /tmp/x86_64-linux-musl
COMMON_CONFIG += CC="gcc -static --static"
COMMON_CONFIG += CXX="g++ -static --static"
EOF
  make clean
  time make -j$(nproc) >/tmp/x86_64-linux-musl-build.out 2>&1 \
  && time make install >>/tmp/x86_64-linux-musl-build.out 2>&1
fi

# aarch64 cross compiler - host is x86_64, uses the toolchain we just built
if [ ! -e /tmp/aarch64-linux-musl-cross ] ; then
  cat>config.mak<<EOF
TARGET = aarch64-linux-musl
OUTPUT = /tmp/aarch64-linux-musl-cross
COMMON_CONFIG += CC="/tmp/x86_64-linux-musl/bin/x86_64-linux-musl-gcc -static --static"
COMMON_CONFIG += CXX="/tmp/x86_64-linux-musl/bin/x86_64-linux-musl-g++ -static --static"
EOF
  make clean
  time make -j$(nproc) >/tmp/aarch64-linux-musl-cross.out 2>&1 \
  && time make install >>/tmp/aarch64-linux-musl-cross.out 2>&1
fi
```

Should build and output two sets of static compilers:

```
/tmp/aarch64-linux-musl-cross/bin/aarch64-linux-musl-g++: ELF executable, 64-bit LSB x86-64, static, not stripped
/tmp/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc: ELF executable, 64-bit LSB x86-64, static, not stripped
/tmp/x86_64-linux-musl/bin/x86_64-linux-musl-g++:         ELF executable, 64-bit LSB x86-64, static, BuildID=147e16a6501360e7e4b24f50ec1ff7cf61ee6fdd, not stripped
/tmp/x86_64-linux-musl/bin/x86_64-linux-musl-gcc:         ELF executable, 64-bit LSB x86-64, static, BuildID=a601e81373bf0b6f1753dda466ed69c5758eed4b, not stripped
```

I believe you can use the same `OUTPUT` to build both sets of compilers and install to the same directory.

But if you're attempting to build an aarch64 native compiler from an aarch64 cross-compiler running on x86_64, i.e.

- x86_64 (native x86_64) -> aarch64 (cross on x86_64) -> aarch64 (native aarch64)

... all bets are off. At least on older versions of GCC, an ARM-specific symbol would be used but not defined. This is most similar to a "Canadian cross" setup, and I'm not sure that'll work here, but I'm not sure. Old post on the issue:

- https://linaro-toolchain.linaro.narkive.com/mealwez3/cross-compilation-issue#post1

**Comment by skychengzhixing** [comment]
Thank you very much for your help！
My goal is to use x86_ 64 compiled on the aarch64 system is the tool chain of aarch64;
I can succeed by following the following steps:

1. I compile dynamic x86_ 64 Linux musl, 
2.  then use  x86_64-linux-musl-gcc and x86_64-linux-musl-g++ in dynamic x86_ 64 Linux musl to compile the static aarch64 Linux musl is successful;

If I compile as follows:
TARGET = x86_64-linux-musl
OUTPUT = /tmp/x86_64-linux-musl
COMMON_CONFIG += CC="gcc -static --static"
COMMON_CONFIG += CXX="g++ -static --static"
EOF

I use my own GCC, the following errors will be reported：
configure:5300: g++ -static --static -E  conftest.cpp
conftest.cpp:9:10: fatal error: ac_nonexistent.h: No such file or directory
    9 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:5300: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:5325: result: g++ -static --static -E
configure:5345: g++ -static --static -E  conftest.cpp
configure:5345: $? = 0
configure:5359: g++ -static --static -E  conftest.cpp
conftest.cpp:9:10: fatal error: ac_nonexistent.h: No such file or directory
    9 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:5359: $? = 1
configure: failed program was:

What causes this?

**Comment by skychengzhixing** [comment]
hi，friend：
The tool chain I compiled lacks three binary files:
Compared with your tool chain, the tool chain I compiled lacks three binary files in the output directory（output/bin）:
aarch64-linux-musl-dwp
aarch64-linux-musl-gfortran
aarch64-linux-musl-ld.gold

What is the cause of this problem?
