### ISSUE TITLE
Can the generated tool chain generate tools containing the ldconfig command set？

### ISSUE THREAD

**Issue by skychengzhixing** [richfelker/musl-cross-make#154]
hi，friend：
Ask a question, Can the generated tool chain generate tools containing the ldconfig command set？Is ldconfig also in binutils toolset?
I want to use the ldconfig command. Can I generate this command set tool? If it can be generated, how are the parameters configured?
give an example:
there is strip command in musl-cross-make/output/aarch64-linux-musl/bin；I want to ldconfig command？

best wish！

**Comment by rofl0r** [comment]
musl doesn't require/use ldconfig, but alpine has a mostly no-op impl: https://git.alpinelinux.org/aports/tree/main/musl/ldconfig
