### ISSUE TITLE
Questions about "gmp, mpc, mpfr" build

### ISSUE THREAD

**Issue by wisonye** [richfelker/musl-cross-make#165]
Hi there, just gently ask about `gmp, mpc, mpfr` in `config.mak`, as I'm not familiar with any of them:)

Here is my `config.mak`:

```config
TARGET = x86_64-linux-musl
OUTPUT = /usr/local
DL_CMD = curl -C - -L -o
```

I run `gmake` in `FreeBSD`, everything works fine, I use the generated `x86_64-linux-musl-gcc` as `musl-gcc` to cross-compile my rust project and run the MUSL binary inside an `Alpine Linux` container, and it works very well.

But I notice that the `gmake` building process took around ... `20min` to finish on an `Intel i5, 32MB RAM` desktop.

Of course, I didn't use `time gmake` to calculate, so `20min` is just an approximate feeling by looking at the clock:)

So, I start to think I should use the following `config.mak`:

```config
TARGET = x86_64-linux-musl
OUTPUT = /usr/local
DL_CMD = curl -C - -L -o
GMP_VER =
MPC_VER =
MPFR_VER =
ISL_VER =
LINUX_VER =
```

Could anyone tell me something about the `gmp, mpc, mpfr`? Or say based on what requirement or condition to determine whether I need those or not?

Many thanks:)

**Comment by ryanwoodsmall** [comment]
GNU's GCC prerequisites page at https://gcc.gnu.org/install/prerequisites.html has notes with links. Long story short, they're libraries for fixed/floating/arbitrary/multi-precision/etc. arithmetic, and they're necessary.

The `Makefile` sets some default versions: https://github.com/richfelker/musl-cross-make/blob/master/Makefile#L8-L10

If you're compiling the compilers a lot, putting `ccache` or similar in your PATH can cache at least partial contents of compiles. That will only help so much though.

**Comment by wisonye** [comment]
> GNU's GCC prerequisites page at https://gcc.gnu.org/install/prerequisites.html has notes with links. Long story short, they're libraries for fixed/floating/arbitrary/multi-precision/etc. arithmetic, and they're necessary.
> 
> 
> 
> The `Makefile` sets some default versions: https://github.com/richfelker/musl-cross-make/blob/master/Makefile#L8-L10
> 
> 
> 
> If you're compiling the compilers a lot, putting `ccache` or similar in your PATH can cache at least partial contents of compiles. That will only help so much though.

Yup, thanks for the quick reply, totally understand now, happy Christmas🥳
