### ISSUE TITLE
Creating native compiler fails (x86-64 RHEL 9.2, x86-64 Alpine)

### ISSUE THREAD

**Issue by DubbleClick** [richfelker/musl-cross-make#175]
(GCC version set to 11.2.0)

I can create a cross compiler for x86_64 using `CFLAGS="-fPIE" make install TARGET=x86_64-linux-musl -j`. I then move the output folder to /usr/local/musl and `export PATH=/usr/local/musl/bin:$PATH".
Attempting to compile a native compiler with `CFLAGS="-fPIE" make install TARGET=x86_64-linux-musl NATIVE=y -j` fails however, with various errors.

I just want a gcc/g++ toolchain targeting musl libraries. I do not plan on cross-compiling. I would use the pre-compiled ones on https://musl.cc, but when compiling php with intl, it causes a segmentation fault somewhere in the musl libraries. This problem does not exist when building this repo myself.

**Comment by casimcdaniels** [comment]
Did you ever figure it out?

**Comment by DubbleClick** [comment]
Yes, after it fails you can find error messages in a gcc config.log. Something about calloc being poisoned. Removing that from gcc source makes compilation run through.

Wasn't an issue when using GCC 13 anymore, by the way, but you'll have to patch the repo with the new checksum.

**Comment by DubbleClick** [comment]
Oh wait, this was the runtime issue after it successfully built: no, never figured it out. Rebuilding with newer versions and installing musl libraries fixed that.

**Comment by meator** [comment]
I have also dealt with this issue. It looks like building an older GCC using a new GCC can lead to problems. The current default GCC version is `9.4.0`, the latest is `15.1` (with `14.2` being widely available). Upgrading `GCC_VER` to `14.2.0` (which matched my host compiler) solved the issue for me.

It looks like #203 will solve this issue once it's merged.

**Comment by meator** [comment]
To my knowledge, zig is just clang, and their first-party cross compilation support is pretty limited, which means that a proper sysroot is still necessary to cross compile. This doesn't give zig any advantage over clang/LLVM.

**Comment by henderkes** [comment]
No, you don't need any sysroot. Zig can compile to nearly all common platforms on the fly. It does to by shipping with versioned source information that it builds on the fly. The only common target it doesn't support is msvc windows (it supports mingw).

**Comment by henderkes** [comment]
```bash
[m@M-TH build]$ echo '#include <iostream>
int main() { std::cout << "Hello World!\n"; }' >> hello.cpp
[m@M-TH build]$ zig c++ -target x86_64-linux-gnu hello.cpp -o gnu
[m@M-TH build]$ zig c++ -target x86_64-linux-musl hello.cpp -o musl
[m@M-TH build]$ zig c++ -target x86_64-linux-gnu.2.17 hello.cpp -o oldgnu
[m@M-TH build]$ zig c++ -target x86_64-windows hello.cpp -o windows.exe
[m@M-TH build]$ zig c++ -target x86_64-linux-musl -dynamic hello.cpp -o musldyn
[m@M-TH build]$ zig c++ -target x86_64-macos -dynamic hello.cpp -o macos
[m@M-TH build]$ ./gnu # can be used on glibc >= 2.39 (rhel 10)
Hello World!
[m@M-TH build]$ ./oldgnu # can be used on glibc >= 2.17
Hello World!
[m@M-TH build]$ ./musl # can be used on all linux systems
Hello World!
[m@M-TH build]$ ./musldyn # musl-libc installed
Hello World!
[m@M-TH build]$ ./windows.exe # binfmt
Hello World!
[m@M-TH build]$ ./macos 
-bash: ./macos: cannot execute binary file: Exec format error
[m@M-TH build]$ file gnu oldgnu musl musldyn macos windows.exe 
gnu:         ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.0.0, with debug_info, not stripped
oldgnu:      ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.0.0, with debug_info, not stripped
musl:        ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
musldyn:     ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
macos:       Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|NO_REEXPORTED_DYLIBS|PIE|HAS_TLV_DESCRIPTORS>
windows.exe: PE32+ executable (console) x86-64, for MS Windows, 7 sections
```
