### ISSUE TITLE
No rule to make target musl-1.2.4

### ISSUE THREAD

**Issue by madobb** [richfelker/musl-cross-make#183]
Hello, if I enter the the newest version of musl 1.2.4 as the MUSL_VER in the config.mak or the Makefile an make error occurs which says: no No rule to make target 'musl-1.2.4', needed by 'all'.  Stop.
My configuration looks like this:
`TARGET = arm-linux-musleabihf  
MUSL_VER = 1.2.4  
`
But if i download musl-1.2.4 from https://musl.libc.org/releases/ and unpack it into the directory it works.
So there is probably a problem downloading the newest version of musl?

**Comment by richfelker** [comment]
Fixed by 2519caabc0ab1438662d2bcde493797e58cd290a
