### ISSUE TITLE
Custom location for ld-musl-aarch64.so.1 (prefix, exec-prefix, and syslibdir)

### ISSUE THREAD

**Issue by 13BTurbo** [richfelker/musl-cross-make#193]
I have a target system that I have no control over and no root access to most parts of the file system.
It's a strange system with an aarch64 CPU and kernel, but an armel operating system.

I have root access to a /user folder and am wanting to compile a custom version of Python3 that is dynamically linked to musl, but utilising /user/lib as the syslibdir and /user as prefix and exec-prefix.

How do I set these custom locations? Do I need to do this while building musl-cross-make or just when compiling Python?
How do I ensure that /user/lib/ is the hard coded location for ld-musl-aarch64.so.1 in the resultant compiled binaries?

Thanks.

**Comment by rofl0r** [comment]
i'd just use patchelf to fix the interpreter after the build...

**Comment by 13BTurbo** [comment]
Thanks so much, I'm a noob when it comes to this stuff.

So I have successfully patched Python with --set-interpreter, --set-rpath, and --no-default-lib.
I've done similar to all the libraries in /user/lib and /user/lib/python3.12/lib-dynload/

Python on the target now runs, however, it appears that Python or it's libraries are still picking up the /lib or /usr/lib folder of the target system.

Is there something else I'm possibly missing that will tell Python or other libs to ignore /lib;/usr/lib and only use /user/lib?

```console
Python 3.12.7 (main, Nov 19 2024, 16:45:15) [GCC 13.2.1 20240309] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import binascii
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Error loading shared library libz.so.1: Exec format error (needed by /user/lib/python3.12/lib-dynload/binascii.cpython-312-aarch64-linux-musl.so)
>>> quit()
```
```console
readelf -d binascii.cpython-312-aarch64-linux-musl.so

Dynamic section at offset 0x40808 contains 25 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [/user/lib]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.musl-aarch64.so.1]
 0x000000000000000c (INIT)               0x1548
 0x000000000000000d (FINI)               0x44f4
 0x0000000000000019 (INIT_ARRAY)         0x1fbc0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x1fbc8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x30028
 0x0000000000000005 (STRTAB)             0x304c0
 0x0000000000000006 (SYMTAB)             0x30058
 0x000000000000000a (STRSZ)              834 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x1fe78
 0x0000000000000002 (PLTRELSZ)           840 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x1200
 0x0000000000000007 (RELA)               0x9c0
 0x0000000000000008 (RELASZ)             2112 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW NODEFLIB
 0x000000006ffffff9 (RELACOUNT)          79
 0x0000000000000000 (NULL)               0x0
```

Cheers.

**Comment by tlaurion** [comment]
I'm interested into your build recipes, having similar goal of building CPython, customized to be really minimal for Heads for a long time.

**Comment by 13BTurbo** [comment]
Putting absolute paths in the python lib-dyn .so files seems to have done the trick!

@tlaurion, I'm using a stock Alpine "virtual" image install running in an aarch64 Proxmox VM. I just compiled Python from source with --prefix=/user, then, as suggested, started messing with the executable and libraries using patchelf.
