### ISSUE TITLE
deterministic-archives

### ISSUE THREAD

**Issue by rofl0r** [richfelker/musl-cross-make#26]
i'd like to propose to either add `--enable-deterministic-archives` to binutils' configure flags either by default, or at least having it as a pre-fabricated (commented out) statement in `config.mak.dist`.

that flag makes it so that ar doesn't embed timestamps into archives, so you can have reproducible builds with the resulting toolchain.

the flag is supported by all binutils version back to 2.20 AFAIK.

since there's no BINUTILS_CONFIG i've not yet come up with a patch.

RFC.

**Comment by richfelker** [comment]
I agree completely. Just add it to the FULL_TOOLCHAIN_CONFIG. Because gcc/binutils are built as a combined-tree, there's no separate config for binutils.

**Comment by rofl0r** [comment]
https://github.com/richfelker/musl-cross-make/commit/a14e91fef8603564a3fea60a65aa1cde8802f9ff
