### ISSUE TITLE
OS X 10.13 build of mips-linux-muslsf fails with (sed: illegal option -- r)

### ISSUE THREAD

**Issue by DJDan** [richfelker/musl-cross-make#39]
OS X 10.13 build of mips-linux-muslsf fails with (sed: illegal option -- r) at end.
Trying to cross compile in OS X 10.13 to be able to use on a mips based router.

config.mak has the following.
TARGET = mips-linux-muslsf

Please let me know when this has been fixed and I can try recompile it from the source.

===

This is the last part of the script.

touch obj_toolchain/.lc_built
ln -sf "../../../linux-4.4.10" src_kernel_headers
mkdir -p /Users/Daniel/Downloads/musl-cross-make/build/local/mips-linux-muslsf/obj_kernel_headers/staged
cd src_kernel_headers && /Applications/Programming/Xcode.app/Contents/Developer/usr/bin/make MULTILIB_OSDIRNAMES= INFO_DEPS= infodir= ac_cv_prog_lex_root=lex.yy.c MAKEINFO=false ARCH=mips O=/Users/Daniel/Downloads/musl-cross-make/build/local/mips-linux-muslsf/obj_kernel_headers INSTALL_HDR_PATH=/Users/Daniel/Downloads/musl-cross-make/build/local/mips-linux-muslsf/obj_kernel_headers/staged headers_install
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  HOSTCC  scripts/basic/fixdep
  WRAP    arch/mips/include/generated/asm/cputime.h
  WRAP    arch/mips/include/generated/asm/current.h
  WRAP    arch/mips/include/generated/asm/dma-contiguous.h
  WRAP    arch/mips/include/generated/asm/emergency-restart.h
  WRAP    arch/mips/include/generated/asm/irq_work.h
  WRAP    arch/mips/include/generated/asm/local64.h
  WRAP    arch/mips/include/generated/asm/mcs_spinlock.h
  WRAP    arch/mips/include/generated/asm/mm-arch-hooks.h
  WRAP    arch/mips/include/generated/asm/mutex.h
  WRAP    arch/mips/include/generated/asm/parport.h
  WRAP    arch/mips/include/generated/asm/percpu.h
  WRAP    arch/mips/include/generated/asm/preempt.h
  WRAP    arch/mips/include/generated/asm/sections.h
  WRAP    arch/mips/include/generated/asm/segment.h
  WRAP    arch/mips/include/generated/asm/serial.h
  WRAP    arch/mips/include/generated/asm/trace_clock.h
  WRAP    arch/mips/include/generated/asm/user.h
  WRAP    arch/mips/include/generated/asm/word-at-a-time.h
  WRAP    arch/mips/include/generated/asm/xor.h
  WRAP    arch/mips/include/generated/uapi/asm/ipcbuf.h
  HOSTCC  scripts/unifdef
  INSTALL include/asm-generic (35 files)
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
make[5]: *** [/Users/Daniel/Downloads/musl-cross-make/build/local/mips-linux-muslsf/obj_kernel_headers/staged/include/asm-generic/.install] Error 1
make[4]: *** [asm-generic] Error 2
make[3]: *** [headers_install] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [obj_kernel_headers/.lc_built] Error 2
make: *** [all] Error 2

**Comment by rofl0r** [comment]
linux kernel headers are outside of our control, so we can't fix it.
but you could send a mail to linux kernel mailing list complaining about it there.
as a quick fix, install gnu-sed with homebrew.
you can also disable the build of the kernel headers completely by using `LINUX_VER=` (i.e. setting the var to empty) and then manually install https://github.com/sabotage-linux/kernel-headers into your crosscompiler prefix, if you need them. the latter do not require a huge download, gnu sed, nor a case-sensitive filesystem.

**Comment by richfelker** [comment]
What @rofl0r said is a good workaround. You can try submitting a bug report to the kernel but I'm not sure if they treat cross issues like this as a bug. Alternatively you can install GNU sed or some other sed with a -r option locally (e.g. in ~/bin) and add that to the head of your $PATH.

**Comment by michaelforney** [comment]
Coincidentally, I recently sent a patch to the linux-kbuild list to fix this:
https://www.spinics.net/lists/linux-kbuild/msg16542.html

Not sure if they will apply it or not, but for now, you could just drop that patch into patches/linux-4.4.10/.

I also sent a patch for another issue you might run in to:
https://www.spinics.net/lists/linux-kbuild/msg16543.html

**Comment by richfelker** [comment]
Is this issue resolved with newer kernel headers? Support for old headers will be dropped very soon since they're incompatible with time64.

**Comment by michaelforney** [comment]
Yes, the patch was merged for v4.17.

**Comment by richfelker** [comment]
Thanks! Closing since the affected kernel header versions are now removed.
