### ISSUE TITLE
remove musl complex hack

### ISSUE THREAD

**Issue by rofl0r** [richfelker/musl-cross-make#4]
the complex hack should only be applied where needed (i.e. sh2 nommu).

**Comment by richfelker** [comment]
It's actually a bug that affects any nofpu sh targets; not sh2/nommu-specific. I'd like to just find the cause in gcc and patch it there, but I haven't found it yet.

**Comment by rofl0r** [comment]
i don't even remember what this was about, so i guess this can be closed?

**Comment by richfelker** [comment]
Commit 69cadffdec removed the hack.
