### ISSUE TITLE
Suggestion: Integrate LLVM compiler support

### ISSUE THREAD

**Issue by ghost** [richfelker/musl-cross-make#42]
I think LLVM addition to musl-cross-make is good option.

"Compiler switch" example:
`make COMPILER=clang` - to llvm toolchain or `make COMPILER=gcc` - to traditional musl-cross-make option

**Comment by richfelker** [comment]
This would be nice but it's completely outside of scope; building LLVM/clang is a completely different process from building binutils and GCC, and I don't think there's any manner in which it would benefit from trying to shoehorn them into a common build framework.
