### ISSUE TITLE
Question: can we build armv6 ABI for Alpine Linux using this toolchain

### ISSUE THREAD

**Issue by kasper3** [richfelker/musl-cross-make#43]
Apologies in advance if it is unrelated. We are trying to figure out how to get `armv7-alpine-linux-musleabihf` for Alpine Linux ARM32 v7 at https://github.com/dotnet/coreclr/issues/17468. The supported ABI by dotnet runtime atm is v7 for 32 bits and v8 for 64.

Since Alpine Linux armhf only provides `armv6-alpine-linux-musleabihf` for 32-bits targets (armv6 and armv7 devices), we were hoping to compile it ourselves; if possible.

Is this the right place to start? If not, could you suggest what would be the good place to start (if it is possible at all)?

Thanks!

**Comment by richfelker** [comment]
I don't understand what you're asking for. It sounds like you think armv6 and armv7 are different ABIs; they're not. They're just different ISA levels. A toolchain targeting armv6 produces binaries/libraries that are perfectly interlinkable with armv7 ones and vice versa; the only difference is whether additional armv7-only instructions are used (in which case the code only runs on armv7 and up as opposed to armv6 and up). If you have a toolchain targeting armv6, just adding `-march=armv7-a` to the `CFLAGS` will produce binaries optimized for armv7 (at the expense of being able to run on v6).

**Comment by richfelker** [comment]
You don't need a custom toolchain to do this, just `-march=armv7-a`.

**Comment by kasper3** [comment]
Thanks. I tried sessing CFLAGS in CMake: `set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -march=armvv7-a -mcpu=cortex-a8")` for alpine, however, when compiling on Alpine Linux 3.7 `Linux aaf28ea95614 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 armv7l Linux`, I am still running into same invalid instructions error:

```
/coreclr/src/pal/../inc/volatile.h:154:5: error: invalid operand for instruction
    VOLATILE_MEMORY_BARRIER();
    ^
/coreclr/src/pal/../inc/volatile.h:79:49: note: expanded from macro 'VOLATILE_MEMORY_BARRIER'
#define VOLATILE_MEMORY_BARRIER() asm volatile ("dmb ish" : : : "memory")
                                                ^
<inline asm>:1:6: note: instantiated into assembly here
        dmb ish
            ^
1 error generated.
```

**Comment by kasper3** [comment]
I made a simple test:

```c
#include <stdio.h>
int main()
{
   asm volatile ("dmb ish" : : : "memory");
   return 0;
}
```

compiled with `clang test.c -o test.exe -march=armv7-a`, and it worked (without `-march=armv7-a`, it gives the error). It seems like something is wrong with CMake configuration of the project I am trying to build (something is overwriting CFlag). I will check.

Thanks for your help!
