### ISSUE TITLE
'go' language possible?

### ISSUE THREAD

**Issue by BlueMax** [richfelker/musl-cross-make#44]
I'm not sure if that's the correct way but i've tried to enable 'go' language with this 'config.mak':
```
TARGET = arm-linux-musleabihf
COMMON_CONFIG += CFLAGS="-g0 -O2" CXXFLAGS="-g0 -O2" LDFLAGS="-s"
GCC_CONFIG += --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-tune=cortex-a9 --with-mode=thumb
GCC_CONFIG += --enable-threads=posix --disable-nls --enable-languages=c,c++,go
MUSL_CONFIG += CFLAGS="-g0 -O2" CXXFLAGS="-g0 -O2" LDFLAGS="-s"

GCC_VER = 7.2.0
LINUX_VER = 
```
Creating the toolchain with 'make -j4' breaks after some time with:
```
sigtab.go:38:2: error: duplicate value for index 29
  _SIGPOLL:    {_SigNotify, "SIGPOLL: pollable event occurred"},
  ^
../../../src_gcc/libgo/go/runtime/signal_unix.go:395:3: error: range clause must have array, slice, string, map, or channel type
   for i := range sigtable {
   ^
../../../src_gcc/libgo/go/runtime/signal_unix.go:591:2: error: range clause must have array, slice, string, map, or channel type
  for i := range sigtable {
  ^
../../../src_gcc/libgo/go/runtime/signal_unix.go:395:7: error: invalid type for range clause
   for i := range sigtable {
       ^
../../../src_gcc/libgo/go/runtime/signal_unix.go:591:6: error: invalid type for range clause
  for i := range sigtable {
```
Is there anything wrong here or is 'go' maybe not supported by the toolchain?

**Comment by richfelker** [comment]
AFAIK, gccgo is not yet working with musl. There is some interest in making it work, but I don't recall the exact status; asking on the musl libc mailing list would probably get more useful feedback.

**Comment by BlueMax** [comment]
Thanks. Will try that.

**Comment by shifty21** [comment]
@BlueMax did you find something on this? This issue is the closest I have come, which mentions alpine and gccgo apart from https://groups.google.com/g/gofrontend-dev/c/-DfK2VkZ9zE thread. 
@richfelker If you have any update on this please let me know.

I am trying to build gccgo on alpine
gcc version - 10.2.0
alpine - 3.12.0
uname -a  - x86_64 linux

**Comment by BlueMax** [comment]
I haven't gone any further than above but there is an official gcc-go package in Alpine repos so it should work out of the box already.
https://pkgs.alpinelinux.org/package/edge/main/x86_64/gcc-go

**Comment by shifty21** [comment]
Thanks for pointing that out, I will give that a try.
