### ISSUE TITLE
Raspberry Pi 3 ARM - ELF format wrong

### ISSUE THREAD

**Issue by mzdunek92** [richfelker/musl-cross-make#45]
Hello,

I have installed your cross compiler using brew:
`brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-arm-hf`

Everything finished successfully.
After that I wrote simple code in Eclipse:

```
#include <iostream>

int main() {
	std::cout << "HELLO" << std::endl;
	return 0;
}
```

Then I have set all needed project options.
Eclipse compiled it with:
`arm-linux-musleabihf-g++ -static -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"main.d" -MT"main.o" -o "main.o" "../main.cpp"`

After copying exec to Raspberry Pi 3 model B I got error:
`-bash: test: No such file or directory
`

So I read ELF and the only thing that is different in this exec is this line:
`OS/ABI:                            UNIX - System V`
while in another working exec's on my Raspberry this is `Unix - GNU`

What can I do to resolve this issue?

**Comment by richfelker** [comment]
You showed the command line used to compile but not the one used to link. It sounds like you intended to static-link, but didn't; the ENOENT error comes from the dynamic linker not being present. Use `readelf -hl ./test` and you'll probably see an `INTERP` header which indicates the program is dynamic-linked. You probably just need to move `-static` from the "compiler flags" to the "linking flags" or similar in Eclipse; I'm not familiar with its UI though.

**Comment by mzdunek92** [comment]
Thank you very much for the reply!

It was Eclipse issue, -static flag had to be included manually in full linking path.
