### ISSUE TITLE
Please set  ELF interpreter so things work, i.e. to output or prefix.

### ISSUE THREAD

**Issue by jaykrell** [richfelker/musl-cross-make#46]
Preferably when I run make install, but even if before that, ok.
I'm giving up a nd trying musl-cross instead of musl-cross-make.
CFLAGS=-static didn't work in my build environment and I'm not sure I want it anyway.
Also putting muslc in /lib didn't work. I didn't debug  it.

**Comment by rofl0r** [comment]
the elf interpreter is already set correctly, it is set to /lib/ld-musl-XXXX.so.1

so when you cross-compile for some target, you need to install the interpreter manually to that target in that path (you can grab it out of the cross-compiler prefix)

**Comment by jaykrell** [comment]
Not cross compiling. A parallel system on current debian/ubuntu/glibc. I had it working well but I forget how. Trying Alpine instead now. :(

**Comment by jaykrell** [comment]
I mean, I understand it is a fine
line between cross & chroot, but I don’t even want chroot. Another angle is the “gcc wrapper” doesn’t support C++. I need C++. I prefer dynamic for overall size optimization. Would prefer to stay in Ubuntu but will use Alpine again.

**Comment by rofl0r** [comment]
if you need C++ support, then you need a full musl-targeting toolchain (in other words, a cross-compiler; and that nomenclature stands even if you want to produce binaries for the same architecture). and as said previously, you need to copy the libc.so and ld-musl-ARCH.so.1 symlink from the cross-compiler directory structure to the target.

**Comment by jaykrell** [comment]
If I set prefix, and make install..? Like, the interpreter path should be what? I guess again it is a fine line, like prefix for the compiler vs. prefix for its outputs. I did try copy & it didn’t work, got a jump to null I think. Maybe I’ll try again.

I get that a partial musl system within a complete glibc system isn’t really valid. I’ll try alpine..

**Comment by rofl0r** [comment]
if you want to use a different "prefix" to install your libs and headers into than the one the cross-compiler natively uses, than that's not really what the compiler authors had in mind. It is possible to some extent by using custom LDFLAGS and CFLAGS that use -isystem and -L directives that point into your desired prefix, but that usage is quite advanced (if you want to know in detail how it works, then checkout the README from the [sabotage-linux repo](https://github.com/sabotage-linux/sabotage), read the section about cross-compilation, and take a look at KEEP/config.cross).
i would however recommend you to install all libs into the cross-compiler "prefix" and copy them to the target once everything's built. here's a script i made for someone else, maybe you can adapt it to your needs: http://ix.io/1dDU

**Comment by osresearch** [comment]
Where is the ELF interpreter set? The executables that are being produced by my build have it set as `/lib/ld-`.  If I create that as a symlink, it works, although I'd also prefer to have the correct value there.

```
# /tmp/musl-cross/bin/x86_64-linux-musl-gcc hello.c 
# file a.out
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, not stripped
```

**Comment by osresearch** [comment]
Although I'm confused why that is happening, since `gcc -v` shows that `collect2` is being invoked with the correct path:
```
/tmp/musl-cross/bin/../libexec/gcc/x86_64-linux-musl/8.3.0/collect2 \
  -plugin /tmp/musl-cross/bin/../libexec/gcc/x86_64-linux-musl/8.3.0/liblto_plugin.so \
  -plugin-opt=/tmp/musl-cross/bin/../libexec/gcc/x86_64-linux-musl/8.3.0/lto-wrapper \
  -plugin-opt=-fresolution=/tmp/ccQkMC3s.res \
  -plugin-opt=-pass-through=-lgcc \
  -plugin-opt=-pass-through=-lgcc_s \
  -plugin-opt=-pass-through=-lc \
  -plugin-opt=-pass-through=-lgcc \
  -plugin-opt=-pass-through=-lgcc_s \
  --sysroot=/tmp/musl-cross/bin/../x86_64-linux-musl \
  --eh-frame-hdr \
  -m elf_x86_64 \
  -dynamic-linker \
  /lib/ld-musl-x86_64.so.1 \
  /tmp/musl-cross/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/crt1.o \
  /tmp/musl-cross/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/crti.o \
  /tmp/musl-cross/bin/../lib/gcc/x86_64-linux-musl/8.3.0/crtbegin.o \
  -L/tmp/musl-cross/bin/../lib/gcc/x86_64-linux-musl/8.3.0 \
  -L/tmp/musl-cross/bin/../lib/gcc \
  -L/tmp/musl-cross/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib \
  -L/tmp/musl-cross/bin/../x86_64-linux-musl/lib \
  /tmp/ccbwCFcY.o \
  -lgcc \
  --as-needed \
  -lgcc_s \
  --no-as-needed \
  -lc \
  -lgcc \
  --as-needed \
  -lgcc_s \
  --no-as-needed \
  /tmp/musl-cross/bin/../lib/gcc/x86_64-linux-musl/8.3.0/crtend.o \
  /tmp/musl-cross/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/crtn.o
```

**Comment by rofl0r** [comment]
https://github.com/richfelker/musl-cross-make/blob/master/patches/gcc-5.3.0/0001-musl.diff#L142

newer gccs already support musl out of the box, but this should be roughly where the value comes from.

**Comment by richfelker** [comment]
You can override this when compiling with the toolchain by putting `-Wl,--dynamic-linker,[pathname]` in the `LDFLAGS`, but GCC doesn't have any way to configure an alternate ldso path, and it's not really my intent to support/encourage this usage except as a very explicit, non-default thing.

There is an open project in musl to support dynamic linking without a `PT_INTERP`, searching for ldso relative to the executable, which may make sense to support as a default in the future and which would meet your need very well, I think. But I'm closing this issue for now because I don't see any reasonable action to take on it at present.
