### ISSUE TITLE
GCC Updates

### ISSUE THREAD

**Issue by JL2210** [richfelker/musl-cross-make#61]
Moved from GregorR/musl-cross#73

I'm coming across several errors when manually building GCC 8.2.0. I was hoping you could possibly provide patches. Issues during `make all-target-libgcc` phase. See https://preshing.com/20141119/how-to-build-a-gcc-cross-compiler/ for more details.

Target system: `x86_64-pc-linux-musl`

Trying to build GCC version: `8.2.0`

Host GCC version: `7.3.0`

Binutils: `2.31.1`

Musl: `1.1.21`

Host GCC configure: `../configure --prefix=/usr/local --libdir=/usr/local/lib64 --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --enable-checking=release --disable-multilib --enable-threads=posix --disable-bootstrap --disable-werror --disable-libmpx --enable-static --enable-shared --program-suffix=-7.3 --with-arch-64=x86-64 --with-default-libstdcxx-abi=gcc4-compatible`

Target GCC configure: `../configure --prefix=/usr/local/musl --target=x86_64-pc-linux-musl --disable-static --enable-shared --enable-host-shared --enable-multilib --with-multilib-list=m32,m64 --with-system-zlib --with-system-libunwind --enable-default-pie --enable-default-ssp --enable-libssp --enable-linker-build-id --enable-version-specific-runtime-libs --enable-initfini-array --enable-ld --enable-gold=default --enable-__cxa_atexit --enable-checking=release --with-default-libstdcxx-abi=new --enable-libstdcxx-filesystem-ts --enable-libstdcxx-threads --enable-libstdcxx-time --enable-clocale --enable-libstdcxx-pch --enable-lto --enable-languages=all`

Host platform: [Chromebrew](https://github.com/skycocker/chromebrew) (`x86_64-cros-linux-gnu`)

**Comment by JL2210** [comment]
That's the system I'm building from.

**Comment by JL2210** [comment]
> support for 8.x has not been merged yet.

Does that imply that it's in the works? If so, may I help?

**Comment by rofl0r** [comment]
the patches are here: http://port70.net/~nsz/musl/gcc-8.2.0/
i guess you could add them to mcm, add the sha file for the gcc 8.2.0 tarball, and try it out. if everything works you could open a PR.

**Comment by JL2210** [comment]
Thanks. I'll check that out.

**Comment by richfelker** [comment]
GCC 8.3.0 and 9.2.0 are now supported so I think this is resolved and I'm closing the issue. Please reopen if this is a mistake.
