### ISSUE TITLE
Fails during libstdc+-v3/src/makefile

### ISSUE THREAD

**Issue by scsijon** [richfelker/musl-cross-make#63]
from the prev line
Building your musl-cross-master (current, not archive) I am failing at this point, can you help please? I will add other details and the makefile and log if wanted.

rm -f libstdc++-symbols.ver.tmp
make[7]: *** No rule to make target '../src/c++11/libc++11convenience.la', needed by 'libstdc++.la'. Stop
make[7]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src'
make[6]: *** [Makefile:638: all-recursive] Error1

and it steps up from there as Error1, Error2....

My intent is to eventually try to replace gcc with the pcc [url]http://pcc.ludd.ltu.se/ftp/pub/pcc/[/url] with pcc-libs [url]http://pcc.ludd.ltu.se/ftp/pub/pcc-libs/[/url], and i'm looking at a basic toolchain to play with / try it out. I will need to update linux to v5 at some point to make best use of it.

But I need to get to the point of a stable working toolchain first.

**Comment by richfelker** [comment]
Can you describe how you're invoking the build? Just the error message without any indication of what you're doing doesn't tell anything about the cause.

**Comment by scsijon** [comment]
Thought you'd need more, but was not sure what. What I did was>

I'm running on the latest Easy Linux, but not in a container.

-downloaded from https://github.com/richfelker/musl-cross-make
-moved it to /mnt/sda6/pcc-musl 
-changed the config.mak to x86_64-linux-musl, removed hash from lines 59 and 64 to run, 
-ran make

Everything went well till this point of failure

last few lines from log follow
----------------------------------
libtool: compile:  /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -shared-libgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc -nostdinc++ -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src/.libs -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/libsupc++/.libs -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include/x86_64-linux-musl -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/libsupc++ -std=gnu++98 -fPIC -DPIC -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-thread-c++0x.lo -g -O2 -D_GNU_SOURCE -std=gnu++11 -c ../../../../src_gcc/libstdc++-v3/src/c++11/compatibility-thread-c++0x.cc -o compatibility-thread-c++0x.o >/dev/null 2>&1
/bin/sh ../libtool --tag CXX   --mode=compile /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -shared-libgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc -nostdinc++ -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src/.libs -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/libsupc++/.libs -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot    -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include/x86_64-linux-musl -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/libsupc++   -std=gnu++98 -fPIC -DPIC -fno-implicit-templates  -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi  -fdiagnostics-show-location=once   -ffunction-sections -fdata-sections  -frandom-seed=compatibility-chrono.lo -g -O2 -D_GNU_SOURCE  -std=gnu++11 -c ../../../../src_gcc/libstdc++-v3/src/c++11/compatibility-chrono.cc
libtool: compile:  /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -shared-libgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc -nostdinc++ -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src/.libs -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/libsupc++/.libs -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include/x86_64-linux-musl -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/libsupc++ -std=gnu++98 -fPIC -DPIC -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-chrono.lo -g -O2 -D_GNU_SOURCE -std=gnu++11 -c ../../../../src_gcc/libstdc++-v3/src/c++11/compatibility-chrono.cc  -fPIC -DPIC -D_GLIBCXX_SHARED -o .libs/compatibility-chrono.o
libtool: compile:  /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -shared-libgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc -nostdinc++ -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src/.libs -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/libsupc++/.libs -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include/x86_64-linux-musl -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/libsupc++ -std=gnu++98 -fPIC -DPIC -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-chrono.lo -g -O2 -D_GNU_SOURCE -std=gnu++11 -c ../../../../src_gcc/libstdc++-v3/src/c++11/compatibility-chrono.cc -o compatibility-chrono.o >/dev/null 2>&1
/bin/sh ../libtool --tag CXX   --mode=compile /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -shared-libgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc -nostdinc++ -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src/.libs -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/libsupc++/.libs -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot    -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include/x86_64-linux-musl -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/libsupc++   -std=gnu++98 -fPIC -DPIC -fno-implicit-templates  -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi  -fdiagnostics-show-location=once   -ffunction-sections -fdata-sections  -frandom-seed=compatibility-condvar.lo -g -O2 -D_GNU_SOURCE  -std=gnu++11 -c ../../../../src_gcc/libstdc++-v3/src/c++11/compatibility-condvar.cc
libtool: compile:  /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -shared-libgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc -nostdinc++ -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src/.libs -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/libsupc++/.libs -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include/x86_64-linux-musl -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/libsupc++ -std=gnu++98 -fPIC -DPIC -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-condvar.lo -g -O2 -D_GNU_SOURCE -std=gnu++11 -c ../../../../src_gcc/libstdc++-v3/src/c++11/compatibility-condvar.cc  -fPIC -DPIC -D_GLIBCXX_SHARED -o .libs/compatibility-condvar.o
libtool: compile:  /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -shared-libgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc -nostdinc++ -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src/.libs -L/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/libsupc++/.libs -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include/x86_64-linux-musl -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/include -I/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/libsupc++ -std=gnu++98 -fPIC -DPIC -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-condvar.lo -g -O2 -D_GNU_SOURCE -std=gnu++11 -c ../../../../src_gcc/libstdc++-v3/src/c++11/compatibility-condvar.cc -o compatibility-condvar.o >/dev/null 2>&1
cp /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/src_gcc/libstdc++-v3/config/abi/pre/gnu.ver libstdc++-symbols.ver.tmp
chmod +w libstdc++-symbols.ver.tmp
if test "x../../../../src_gcc/libstdc++-v3/config/abi/pre/float128.ver" != x; then \
  if grep '^# Appended to version file.' \
       ../../../../src_gcc/libstdc++-v3/config/abi/pre/float128.ver > /dev/null 2>&1; then \
    cat ../../../../src_gcc/libstdc++-v3/config/abi/pre/float128.ver >> libstdc++-symbols.ver.tmp; \
  else \
    sed -n '1,/DO NOT DELETE/p' libstdc++-symbols.ver.tmp > tmp.top; \
    sed -n '/DO NOT DELETE/,$p' libstdc++-symbols.ver.tmp > tmp.bottom; \
    cat tmp.top ../../../../src_gcc/libstdc++-v3/config/abi/pre/float128.ver tmp.bottom > libstdc++-symbols.ver.tmp; \
    rm tmp.top tmp.bottom; \
  fi; \
fi
/bin/grep -E -v '^[ 	]*#(#| |$)' libstdc++-symbols.ver.tmp | \
  /mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/xgcc -B/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/./gcc/ -B/x86_64-linux-musl/bin/ -B/x86_64-linux-musl/lib/ -isystem /x86_64-linux-musl/include -isystem /x86_64-linux-musl/sys-include --sysroot=/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_sysroot   -E -P -include ../config.h - > libstdc++-symbols.ver || (rm -f libstdc++-symbols.ver ; exit 1)
rm -f libstdc++-symbols.ver.tmp
make[7]: *** No rule to make target '../src/c++11/libc++11convenience.la', needed by 'libstdc++.la'.  Stop.
make[7]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src'
make[6]: *** [Makefile:638: all-recursive] Error 1
make[6]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3/src'
make[5]: *** [Makefile:507: all-recursive] Error 1
make[5]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3'
make[4]: *** [Makefile:414: all] Error 2
make[4]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc/x86_64-linux-musl/libstdc++-v3'
make[3]: *** [Makefile:11215: all-target-libstdc++-v3] Error 2
make[3]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc'
make[2]: *** [Makefile:886: all] Error 2
make[2]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl/obj_gcc'
make[1]: *** [Makefile:234: obj_gcc/.lc_built] Error 2
make[1]: Leaving directory '/mnt/sda6/pcc-musl/musl-cross-make-master/build/local/x86_64-linux-musl'
make: *** [Makefile:165: all] Error 2
#

**Comment by scsijon** [comment]
Not sure what else to add?

**Comment by scsijon** [comment]
tried to add the related config.log but it wouldn't let me, something about too long.

**Comment by rofl0r** [comment]
i suppose you should attach (or pastebin) your config.mak

**Comment by richfelker** [comment]
The actual config.mak and make command line are what we need to see. Without information about how you're invoking it, any errors/logs are meaningless.

**Comment by scsijon** [comment]
#
# config.mak.dist - sample musl-cross-make configuration
#
# Copy to config.mak and edit as desired.
#

# There is no default TARGET; you must select one here or on the make
# command line. Some examples:

# TARGET = i486-linux-musl
 TARGET = x86_64-linux-musl
# TARGET = arm-linux-musleabi
# TARGET = arm-linux-musleabihf
# TARGET = sh2eb-linux-muslfdpic
# ...

# By default, cross compilers are installed to ./output under the top-level
# musl-cross-make directory and can later be moved wherever you want them.
# To install directly to a specific location, set it here. Multiple targets
# can safely be installed in the same location. Some examples:

# OUTPUT = /opt/cross
# OUTPUT = /usr/local

# By default, latest supported release versions of musl and the toolchain
# components are used. You can override those here, but the version selected
# must be supported (under hashes/ and patches/) to work. For musl, you
# can use "git-refname" (e.g. git-master) instead of a release. Setting a
# blank version for gmp, mpc, mpfr and isl will suppress download and
# in-tree build of these libraries and instead depend on pre-installed
# libraries when available (isl is optional and not set by default).
# Setting a blank version for linux will suppress installation of kernel
# headers, which are not needed unless compiling programs that use them.

# BINUTILS_VER = 2.25.1
# GCC_VER = 5.2.0
# MUSL_VER = git-master
# GMP_VER =
# MPC_VER =
# MPFR_VER =
# ISL_VER =
# LINUX_VER =

# By default source archives are downloaded with wget. curl is also an option.

# DL_CMD = wget -c -O
# DL_CMD = curl -C - -L -o

# Something like the following can be used to produce a static-linked
# toolchain that's deployable to any system with matching arch, using
# an existing musl-targeted cross compiler. This only works if the
# system you build on can natively (or via binfmt_misc and qemu) run
# binaries produced by the existing toolchain (in this example, i486).

# COMMON_CONFIG += CC="i486-linux-musl-gcc -static --static" CXX="i486-linux-musl-g++ -static --static"
# COMMON_CONFIG += CC="x86_64-linux-musl-gcc -static --static" CXX="x86_64-linux-musl-g++ -static --static"

# Recommended options for smaller build for deploying binaries:

 COMMON_CONFIG += CFLAGS="-g0 -Os -fPIC" CXXFLAGS="-g0 -Os" LDFLAGS="-s"

# Recommended options for faster/simpler build:

# COMMON_CONFIG += --disable-nls
 GCC_CONFIG += --enable-languages=c,c++
# GCC_CONFIG += --disable-libquadmath --disable-decimal-float
# GCC_CONFIG += --disable-multilib

# You can keep the local build path out of your toolchain binaries and
# target libraries with the following, but then gdb needs to be told
# where to look for source files.

# COMMON_CONFIG += --with-debug-prefix-map=$(CURDIR)=

---------------------------------------
make command is just 

# make 

as the readme says to do

**Comment by scsijon** [comment]
sorry, the formatting in the config.mak must have played with the formatting, all the hashes have dissapeared?

**Comment by richfelker** [comment]
I fixed the formatting for you

**Comment by scsijon** [comment]
Thanks for the formatting fix, it matches what I see.

The Easy Linux internal versions are>
binutils - 2.28-r0
gcc - 6.3.0-r0
gmp - 6.1.2-r0
linux - 4.14.105
mpc - na
libmpc - 1.0.3-r0
mpfr - 3.1.5-r0
glibc - 2.25-r0
glib - 2.0-1_2.50.3-r0
musl - na

I wonder if it's that?

I tried building it on another box with a different linux (quirky) and it failed at the same point, so I don't, at this point, think it's my end.

**Comment by rofl0r** [comment]
> I tried building it on another box with a different linux (quirky) and it failed at the same point, so I don't, at this point, think it's my end.

works for me on sabotage.
a few weeks ago another quirky user came to the sabotage support channel with issues building sabotage and it turned his glibc headers were bugged. so imo the issue is on your end :)

**Comment by scsijon** [comment]
@rofl0r

Do you know which quirky he was using as they use different bases to compile from?

I have others I will try. By the way Easy Linux is built with OpenEmbeded packages.

Those of us in the puppy world use packages usually compiled by others, we just 'assemble' them into "Linux's" containing what we want to use.

**Comment by rofl0r** [comment]
> Do you know which quirky he was using as they use different bases to compile from?

```
<Guest85655>    sorry about that, https://0x0.st/zzU3.log is the binutils.log
<Guest85655>    what, i'm building on? is a puppy linux called quirky xenial, built from ubuntu-xenial
<rofl0r>    it appears the headers you have installed are buggy
<rofl0r>    can you pastebin the file /usr/include/x86_64-linux-gnu/sys/sysctl.h ?
<Guest85655>    https://0x0.st/zzUk.h
<Guest85655>    our headers are built to match the kernel we use, in this case it's 4.14.17
<rofl0r>    ok try this
<rofl0r>    after #include <features.h>
<rofl0r>    add: #include <sys/cdefs.h>
<Guest85655>    yup, magic, stage0 has completed, thanks
```

**Comment by scsijon** [comment]
@rofl0r, quirky xenial with that kernel means it's Quirky 7.9.0 to 8.4.0, #include <sys/cdefs.h> is  in 8.4.0, but not in 8.3.0.

@ richfelker, i'm beginning to think something's strange my end as rofl0r sugested as i've now built with a number of different based quirky's and those with a T2 base are ok,, those with OpenEmbeded fail as do those with a Ubundu 16.04 LTS. I have a few others to try, but will have to get onto BarryK our Easy Linux's 'Master' and let him know somethings wrong with the OE source builds. He may appear here with questions, but for now I will leave it open for a week and then close it unless something appears.

Thanks to you both

**Comment by JL2210** [comment]
I don't think you can build an older GCC version with a newer version. I've had similar issues.

Also see this link: https://forums.gentoo.org/viewtopic-t-1063494-start-0.html

Try passing `-j1` to the build. Also try disabling ISL/Graphite.

**Comment by rofl0r** [comment]
> I don't think you can build an older GCC version with a newer version

false

> Try passing -j1 to the build.

i've built mcm dozens of times, there are no issues with parallel build (at least not with the defaults, i.e. gcc 6.x, binutils 2.27, etc)

**Comment by scsijon** [comment]
OK, just to finish this off (I think) 
Problems found were>

1 Actual version of kernel-headers didn't match the kernel installed, they were an earlier one, didn't think it mattered, but apparently it does with building toolchains, it's mentioned on a number of systems.
2 no lsl
3 there are hard addresses for "--with-libtool-sysroot" and
"--with-build-sysroot" within ito-wrapper and this affects the sysroot settings when gcc actually builds (rather than configure's settings which are right).

1 and 2 were easy to fix
for 3 at present I have disabled ito

However i'm still getting the> 

make[7]: *** No rule to make target '../src/c++11/libc++11convenience.la', needed by 'libstdc++.la'. Stop.

problem, and are awaiting the new Easy Linux version to see if the problem will be resolved then.
And building with Ubuntu LTS also gives the same results so I don't know what it really is.

**Comment by JL2210** [comment]
Can you give me the output of `g++ -std=c++11`?

**Comment by richfelker** [comment]
The claim that kernel headers need to match the system you're building on is wrong and completely implausible. The system you're building on need not even be Linux. The kernel headers are not used whatsoever during build. Their only purpose is installing them for users who assume a complete cross toolchain includes kernel headers for the target.
