### ISSUE TITLE
Using a gcc and binutils fork from a github branh

### ISSUE THREAD

**Issue by mzpqnxow** [richfelker/musl-cross-make#75]
I'd like to experiment with a musl toolchain for Lexra MIPS CPUs. If you're not familiar with the Lexra abomination, there's a brief explanation at the Linux/MIPS site here:

https://www.linux-mips.org/wiki/Lexra

This is a relatively rare CPU but it is found on a handful of Realtek SoCs, so it is not completely obsolete or exotic. I would like to ditch the binary RSDK made available by Realtek if possible since musl-libc is superior in so many ways

Though these are very old chips, Yasha Cherikovsky is working on getting official support for these chips into upstream GCC / binutils, but for now I am only working with forks on github:

* https://github.com/yashac3/binutils-gdb
* https://github.com/yashac3/gcc

There seems to be a good chance that his work will eventually be accepted based on some mailing list discussions:

* https://lkml.org/lkml/2018/9/30/283
* https://lore.kernel.org/patchwork/cover/993896/

Is there an easy way for me to specify that these should be used with musl-cross-make, or is there a large amount of hand modifying/patching I will need to do the Makefiles? GitHub can very easily emit tarballs by appending "/tarball/<branch>" to the end of the URL, but this doesn't really help since the archives are not named in accordance with what musl would expect. Additionally, I assume I would have to create sha1 sums in the hashes directory.

Is there any approach here that is simpler than stepping through all of the Makefiles and figuring this out on my own? I'm not asking for hand-holding, but perhaps an opinion on how much effort may be required from me and/or a suggested approach (or a suggestion to not bother trying at all!)

Thanks!

**Comment by richfelker** [comment]
You need to add hashes files, patches (if needed; at least invalid_tls_model is needed still if you use the affected libs), and either just pre-populate the sources dir with the tarball or add (via config.mak or changes to top-level makefile) rules for how to get it. I'm a bit confused what this gcc fork is needed for though. It sounds like the only quirk of these chips is the missing unaligned access instructions, which can just be emulated (modulo ridiculous political refusal to do so) and won't appear in any reasonable code anyway.

**Comment by mzpqnxow** [comment]
Great, thank you!

And yep, it is what sounds like an extremely rare case. As it turns out though, a non-negligible amount of embedded products use a series of Realtek SoCs that have this Lexra chip on them. And yeah, you're right, in plenty of instances I've built software with standard GCC that produced no unaligned reads/writes, most of the time it's less than a dozen. But it's very painful to work around manually when doing anything other than maintaining one or two static packages. I won't bore you with my hobbies to explain why this is necessary :)

Thanks again, I very much appreciate the musl project!
