### ISSUE TITLE
Interest in a handful of sample config.mak files as a PR?

### ISSUE THREAD

**Issue by mzpqnxow** [richfelker/musl-cross-make#87]
Hello,

I have had to develop a small/medium handful of different config.mak files over time for projects with various SoCs (just about every architecture except sparc) and I keep a set of `config.mak` files handy.

Do you have any interest in keeping an `examples/` directory in the musl-cross-make repository? If so I would be happy to PR them.

I also have a simple script similar the Python virtualenv `activate` scripts that you use via `$ source /toolchains/musl-x86_64-linux/activate` that sets a bunch of environment variables to make building certain packages much easier, since not all support straightforward cross-compiling conventions in their configure/make systems (if they even have configure/make at all!)

Please let me know if you would be interested in either thing and I will send a PR.

Thank you, I very much appreciate the work you do on musl and musl-cross-make

**Comment by richfelker** [comment]
Examples are likely in-scope. Growing a buildroot isn't, but I could possibly link to a repo of such recipes you want to maintain from the wiki or other docs at some point. Can you show some examples?
