### ISSUE TITLE
shared binaries produced are not executable; loader symlink broken

### ISSUE THREAD

**Issue by 0x8000-0000** [richfelker/musl-cross-make#92]
I have built a toolchain for x86_64-linux-musl using musl-cross-make . I have updated gcc to 9.3.0 and binutils to 2.34 but all other settings are default.

Building a binary works, but running it fails.

Running "file ./foo" I get this "ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, not stripped"

**Comment by richfelker** [comment]
It looks like something's wrong with your updated GCC, since it thinks the name of the dynamic linker should be "/lib/ld-". Try looking at the output of `x86_64-linux-musl-gcc -v ...` compiling/linking your program.

**Comment by 0x8000-0000** [comment]
This time I have only changed TARGET and OUTPUT:

```
~/work/incubator/snippets$ cat hello.c 
#include <stdio.h>

int main()
{
   printf("Hello, world!\n");
   return 0;
}
$ /opt/gcc9musl/bin/x86_64-linux-musl-gcc hello.c
$ file a.out 
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped
$ ./a.out 
zsh: no such file or directory: ./a.out
$ /opt/gcc9musl/bin/x86_64-linux-musl-gcc -v
Using built-in specs.
COLLECT_GCC=/opt/gcc9musl/bin/x86_64-linux-musl-gcc
COLLECT_LTO_WRAPPER=/opt/gcc9musl/bin/../libexec/gcc/x86_64-linux-musl/9.2.0/lto-wrapper
Target: x86_64-linux-musl
Configured with: ../src_gcc/configure --enable-languages=c,c++ --disable-bootstrap --disable-assembly --disable-werror --target=x86_64-linux-musl --prefix= --libdir=/lib --disable-multilib --with-sysroot=/x86_64-linux-musl --enable-tls --disable-libmudflap --disable-libsanitizer --disable-gnu-indirect-function --disable-libmpx --enable-libstdcxx-time=rt --with-build-sysroot=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_sysroot AR_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/ar AS_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/gas/as-new LD_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/ld/ld-new NM_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/nm-new OBJCOPY_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/objcopy OBJDUMP_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/objdump RANLIB_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/ranlib READELF_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/readelf STRIP_FOR_TARGET=/home/florin/tools/musl-cross-make/build/local/x86_64-linux-musl/obj_binutils/binutils/strip-new --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu
Thread model: posix
gcc version 9.2.0 (GCC) 
```

This was built on Debian bullseye (testing) using native gcc/g++ packages.

**Comment by 0x8000-0000** [comment]
This works:

```
$ /opt/gcc9musl/bin/x86_64-linux-musl-gcc -static hello.c
~/work/incubator/snippets$ ls -la a.out 
-rwxr-xr-x 1 florin florin 10400 Mar 26 21:31 a.out
$ file a.out 
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
$ ./a.out 
Hello, world!
```

**Comment by richfelker** [comment]
Oh, it looks ok there. Maybe you just copied it wrong in your original post. If you have dynamic binaries, `ld-musl-$(ARCH).so.1` needs to be installed in `/lib` to run them, or you can invoke it as a command `/path/to/ld-musl-x86_64.so.1 -- ./a.out ...` to run them. Static binaries work with nothing installed.

**Comment by 0x8000-0000** [comment]
In the original post I have installed the binaries with 'make install' after setting OUTPUT variable.

**Comment by 0x8000-0000** [comment]
The plot thickens:

```
$ find /opt/gcc9musl -name ld-musl\*                                
/opt/gcc9musl/x86_64-linux-musl/lib/ld-musl-x86_64.so.1
$ ls -l /opt/gcc9musl/x86_64-linux-musl/lib/ld-musl-x86_64.so.1
lrwxrwxrwx 1 root root 12 Mar 26 19:37 /opt/gcc9musl/x86_64-linux-musl/lib/ld-musl-x86_64.so.1 -> /lib/libc.so
$ file /opt/gcc9musl/x86_64-linux-musl/lib/ld-musl-x86_64.so.1
/opt/gcc9musl/x86_64-linux-musl/lib/ld-musl-x86_64.so.1: broken symbolic link to /lib/libc.so
```

**Comment by 0x8000-0000** [comment]
And this is from the build directory:

```
~/tools/musl-cross-make$ find . -name ld-musl\*
./build/local/x86_64-linux-musl/obj_sysroot/lib/ld-musl-x86_64.so.1
~/tools/musl-cross-make$ ls -la ./build/local/x86_64-linux-musl/obj_sysroot/lib/ld-musl-x86_64.so.1
lrwxrwxrwx 1 florin florin 12 Mar 26 19:09 ./build/local/x86_64-linux-musl/obj_sysroot/lib/ld-musl-x86_64.so.1 -> /lib/libc.so
```

**Comment by 0x8000-0000** [comment]
And for completeness:

```
~/tools/musl-cross-make$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
~/tools/musl-cross-make$ diff config.mak.dist config.mak
11c11
< # TARGET = x86_64-linux-musl
---
> TARGET = x86_64-linux-musl
23a24
> OUTPUT = /opt/gcc9musl
```

**Comment by richfelker** [comment]
Yes, `make install` is not intended to create a setup to run the binaries produced on your system. In the typical case, your host system isn't even capable of running them (e.g. your host is Mac not Linux, or your host is x86_64 and the target is arm or powerpc). Rather it gives you a cross compiler. The ld-musl in the cross compiler output dir is also a broken symlink because it's setup (by musl's `make install`) for the layout of the target filesystem on the target. It's somewhat misleading that it's there at all. There have been some proposals for how to change it that might work better for what you want; the main missing ingredient is a make expression to get the ../'s right to build a relative path for the symlink rather than an absolute one.

**Comment by 0x8000-0000** [comment]
I want a 'cross' environment because I want to isolate the binaries I'm producing from the build environment, to get a 'portable toolchain'.

The question remains: Once I was able to build a shared binary, with this toolchain, what setup do I need on the target system to get that binary to run? Only using MUSL and its interface to the kernel, bypassing glibc ? Does this toolchain provide a loader?

**Comment by 0x8000-0000** [comment]
```
$ gcc hello.c 
$ file a.out
a.out: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=097941869c5db7c3c58668a5c6a7d0ad269d99ca, for GNU/Linux 3.2.0, not stripped
$ /opt/gcc9musl/bin/x86_64-linux-musl-gcc hello.c
$ file a.out 
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped
$ /lib64/ld-linux-x86-64.so.2 ./a.out
./a.out: error while loading shared libraries: /lib/x86_64-linux-gnu/libc.so: invalid ELF header
```

**Comment by richfelker** [comment]
You're trying to use the glibc dynamic linker to load the program. That won't work.

**Comment by 0x8000-0000** [comment]
> You're trying to use the glibc dynamic linker to load the program. That won't work.

That much is clear :)
Does MUSL provide a dynamic linker? If not, should dynamic binaries fail to link?

**Comment by richfelker** [comment]
Yes. On a musl-based system it will already be present in `/lib/ld-musl-x86_64.so.1` (or whatever arch+abi name in place of `x86_64` for other archs). If you want to install it to be able to run musl-linked dynamic binaries on your non-musl-based system, make a copy of or symlink to the musl `libc.so` named `/lib/ld-musl-x86_64.so.1`.

**Comment by 0x8000-0000** [comment]
Confirmed it works. Thank you!
