### ISSUE TITLE
toolchain is missing symbols from signal.h

### ISSUE THREAD

**Issue by 0x8000-0000** [richfelker/musl-cross-make#93]
Not sure if this is a toolchain building problem or a MUSL problem, but I can't find a public issue tracker for MUSL so I'll record this here - apologies if this is not the correct place.

I am building an application with the toolchain, and it fails to compile with these errors:

```
.... : error: ‘SIGEV_THREAD_ID’ was not declared in this scope; did you mean ‘SIGEV_THREAD’?
.... : : error: ‘struct sigevent’ has no member named ‘_sigev_un’
```

I see these symbols available in x86_64-linux-musl/include/asm-generic/siginfo.h, included in linux/signal.h but that file is not included in signal.h .

**Comment by richfelker** [comment]
The musl mailing list would be the right place. I believe there's actually a pending patch for this. The reason it's not presently supported is that whether to offer interfaces that use kernel TIDs (vs `pthread_t` was an open question and we were trying to develop consensus with glibc on whether that was a good idea. I think it's been mostly resolved to support them, so I'll take a look at the patches and whether it makes sense to go forward with them as-is or whether they need any changes to go upstream.
