### ISSUE TITLE
q: does it work using clang

### ISSUE THREAD

**Issue by mobop** [richfelker/musl-cross-make#95]

**Comment by richfelker** [comment]
musl-cross-make is specifically a build system for the GNU toolchain components (binutils and GCC) with musl, particularly for doing it efficiently in a single pass, and patching issues using them with musl that aren't fixed upstream. The procedure for doing this has nothing to do with clang/LLVM build procedures, so no, it doesn't work with clang.

Also, clang is always a cross compiler, so in theory you don't need this kind of elaborate process to get one, but I don't know what a good up-to-date guide on the process is.

**Comment by mobop** [comment]
thanks
